name: litevlm
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip>=23.0
  - numpy>=1.24.0
  - pip:
    - torch>=2.0.0
    - torchvision>=0.15.0
    - transformers>=4.35.0
    - accelerate>=0.24.0
    - optimum>=1.14.0
    - Pillow>=10.0.0
    - opencv-python>=4.8.0
    - timm>=0.9.0
    - onnx>=1.14.0
    - onnxruntime>=1.16.0
    - pycuda>=2022.1
    - tqdm>=4.66.0
    - einops>=0.7.0
    - safetensors>=0.4.0
    - click>=8.1.0
    - pyyaml>=6.0
    - python-dotenv>=1.0.0
    - psutil>=5.9.0
    - pynvml>=11.5.0
